name: simplenewsfeed
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  webfeed: ^0.4.2
  provider: ^3.1.0+1
  http: ^0.12.0+2
  moor_flutter: ^2.1.0


dev_dependencies:
  moor_generator: ^2.1.0
  build_runner: ^1.7.2

  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true